### ISSUE TITLE
how to add other accessories to config.json

### ISSUE THREAD

**Issue by HapCoderWei** [rsg98/homebridge-gpio-wpi#4]
Hello, I want to add some other accessoris to my config.json, maybe a fan, but i don't know how to write it. Could you kindly tell me what could i write and what's the platform in the config.json? Sincerely thanks!

**Comment by rsg98** [comment]
Platform is a new way of writing Homebridge plugins - for an example, you have have a look at the platform version of this plugin rsg98/homebridge-gpio-wpi2

If you want to add more accessories, you need to find plugins that support what you would like to control. Each of those plugins should have a readme or similar on GitHub or npmjs.com that describes how to configure them.

Plugins are generally tagged with the keyword homebridge-plugin on NPM, so searching for them is fairly easy:

https://www.npmjs.com/browse/keyword/homebridge-plugin

**Comment by HapCoderWei** [comment]
ok, thanks for you replay :+1:
